channels:
  - conda-forge
  - bioconda
dependencies:
  - python >=3.5
  - boto3
  - datrie
  - moto >=1.0.1
  - httpretty
  - wrapt
  - pyyaml
  - ftputil
  - pysftp
  - requests
  - dropbox
  - appdirs
  - pytools
  - docutils
  - psutil
  - pandas
  - nomkl
  - google-cloud-storage
  - azure-storage
  - azure-storage-common
  - ratelimiter
  - configargparse
  - appdirs
  - python-irodsclient
  - jsonschema
  - networkx
  - pygraphviz
  # needed by graphviz
  - xorg-libxrender
  - xorg-libxpm
  - gitpython
  - pygments
  - imagemagick
