channels:
  - conda-forge
  - bioconda
dependencies:
  - python >=3.11
  - yte
  - packaging
  - stopit
  - datrie
  - boto3
  - moto =3 # breaking changes in moto 4 that would need an update of S3Mocked
  - junit-xml # needed for S3Mocked
  - httpretty
  - wrapt
  - pyyaml
  - pytest
  - pytest-mock
  - pytest-cov
  - pytest-split
  - ftputil
  - pysftp
  - requests
  - responses
  - dropbox
  - numpy
  - appdirs
  - pytools
  - docutils
  - pygments
  - pandoc
  - xorg-libxrender
  - xorg-libxext
  - xorg-libxau
  - xorg-libxdmcp
  - xorg-libsm
  - psutil
  - google-cloud-storage
  - google-api-python-client
  - oauth2client
  - azure-storage-blob
  - configargparse
  - appdirs
  - python-irodsclient <1.1.2 # bug in 1.1.2 leads to KeyError
  - jsonschema
  - pandas
  - python-kubernetes
  - gitpython
  - pulp >=2.0
  - tibanna
  - environment-modules
  - nbformat
  - toposort >=1.10
  - mamba
  - crc32c
  - connection_pool
  - py-tes
  - requests-mock
  - peppy
  - eido
  - glpk
  - smart_open
  - filelock
  - tabulate
  - reretry
  - graphviz
  - humanfriendly
  - throttler
  - msrest
  - azure-batch
  - azure-mgmt-batch
  - azure-identity
  - nodejs # for cwltool
  - apptainer
  - squashfuse # for apptainer
  - immutables
  - conda
  - pip
    - cwltool
    - cwl-utils
