channels:
  - conda-forge
  - bioconda
dependencies:
  - python >=3.5
  - rpy2 >=0.7.6
  - datrie
  - boto3
  - httpretty
  - wrapt
  - pyyaml
  - pytest
  - ftputil
  - pysftp
  - requests
  - dropbox
  - numpy
  - appdirs
  - pytools
  - docutils
  - pandoc <2.0  # pandoc has changed the CLI API so that it is no longer compatible with the version of r-markdown below
  - r-base >=3.4.1
  - r-rmarkdown =1.6
  - xorg-libxrender
  - xorg-libxext
  - xorg-libxau
  - xorg-libxdmcp
  - xorg-libsm
  - psutil
  - google-cloud-storage
  - ratelimiter
  - configargparse
  - appdirs
  - python-irodsclient
  - cwltool =1.0.20181217162649
  - jsonschema
  - pandas
  - networkx
  - pygraphviz
  - python-kubernetes
  - pip:
      - moto==1.3.5
  - gitpython
