channels:
  - conda-forge
  - bioconda
dependencies:
  - python >=3.5
  - datrie
  - boto3
  - moto
  - httpretty
  - wrapt
  - pyyaml
  - pytest
  - pytest-cov
  - ftputil
  - pysftp
  - requests
  - dropbox
  - numpy
  - appdirs
  - pytools
  - docutils
  - pygments
  - pandoc <2.0  # pandoc has changed the CLI API so that it is no longer compatible with the version of r-markdown below
  - xorg-libxrender
  - xorg-libxext
  - xorg-libxau
  - xorg-libxdmcp
  - xorg-libsm
  - psutil
  - google-cloud-storage
  - google-api-python-client
  - oauth2client
  - azure-storage-blob
  - ratelimiter
  - configargparse
  - appdirs
  - python-irodsclient
  - cwltool
  - jsonschema
  - pandas
  - networkx
  - pygraphviz
  - python-kubernetes
  - gitpython
  - pulp >=2.0
  - tibanna
  - environment-modules
  - nbformat
  - toposort
  - mamba
  - crc32c
  - peppy
  - eido
