channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - python >=3.11
  - mamba
  - yte
  - packaging
  - stopit
  - datrie
  - boto3
  - httpretty
  - wrapt
  - pyyaml
  - pytest
  - pytest-mock
  - pytest-cov
  - pytest-split
  - ftputil
  - pysftp
  - requests
  - responses
  - numpy
  - appdirs
  - pytools
  - docutils
  - pygments
  - pandoc
  - xorg-libxrender
  - xorg-libxext
  - xorg-libxau
  - xorg-libxdmcp
  - xorg-libsm
  - psutil
  - oauth2client
  - configargparse
  - appdirs
  - jsonschema
  - pandas
  - gitpython
  - pulp >=2.3.1
  - environment-modules
  - nbformat
  - toposort >=1.10
  - crc32c
  - requests-mock
  - peppy
  - eido
  - glpk
  - smart_open
  - filelock
  - tabulate
  - reretry
  - graphviz
  - humanfriendly
  - throttler
  - dpath
  - nodejs # for cwltool
  - immutables
  - conda
  - pip
  - pip:
      - cwltool
      - cwl-utils
      - "--editable=https://github.com/snakemake/snakemake-interface-executor-plugins.git@fix/quoting-lists"
      - snakemake-executor-plugin-cluster-generic >=1.0.9
      - snakemake-storage-plugin-http
      - snakemake-storage-plugin-s3
